/**
 * 菜单管理演示数据（纯前端模式）：
 * 本仓库无请求层（CLAUDE.md「项目定位」），菜单管理页按确定性静态数据在页面内存内
 * 渲染与 CRUD——无随机数、无请求；刷新页面后由页面重置回本数据。
 * 菜单与权限点是两套体系，数据不携带权限码；树形与前端静态路由（router/definitions.tsx）
 * 保持同名同径，仅作管理端数据维护演示——菜单管理不动态改变前端静态路由。
 * 数据有意覆盖全部形态：目录/页面/外链、显示/隐藏、启用/停用、有/无图标、有/无子级。
 */
import type { MenuItem } from '@/types/system/menu/menu.types'

/** 演示菜单树：1 个仪表盘页 + 1 个三级系统管理目录（3 子级）+ 停用页 + 隐藏页 + 外链 */
export const MENU_DEMO_TREE: MenuItem[] = [
  {
    id: 'm-dashboard',
    parentId: null,
    menuType: 'page',
    title: '仪表盘',
    name: 'dashboard',
    path: '/dashboard',
    component: 'dashboard/Dashboard',
    icon: 'local:ic-dashboard',
    sortOrder: 1,
    visible: true,
    status: 'active',
    children: [],
    createdAt: '2026-01-05T09:00:00+08:00',
    updatedAt: '2026-06-30T10:20:00+08:00',
  },
  {
    id: 'm-system',
    parentId: null,
    menuType: 'directory',
    title: '系统管理',
    name: null,
    path: '/system',
    component: null,
    icon: 'local:ic-management',
    sortOrder: 10,
    visible: true,
    status: 'active',
    children: [
      {
        id: 'm-system-user',
        parentId: 'm-system',
        menuType: 'page',
        title: '用户管理',
        name: 'system-user',
        path: '/system/user',
        component: 'system/user/User',
        icon: 'local:ic-user',
        sortOrder: 1,
        visible: true,
        status: 'active',
        children: [],
        createdAt: '2026-01-05T09:05:00+08:00',
        updatedAt: '2026-06-30T10:20:00+08:00',
      },
      {
        id: 'm-system-role',
        parentId: 'm-system',
        menuType: 'page',
        title: '角色管理',
        name: 'system-role',
        path: '/system/role',
        component: 'system/role/Role',
        icon: 'local:ic-role',
        sortOrder: 2,
        visible: true,
        status: 'active',
        children: [],
        createdAt: '2026-01-05T09:06:00+08:00',
        updatedAt: '2026-06-30T10:20:00+08:00',
      },
      {
        id: 'm-system-menu',
        parentId: 'm-system',
        menuType: 'page',
        title: '菜单管理',
        name: 'system-menu',
        path: '/system/menu',
        component: 'system/menu/Menu',
        icon: 'local:ic-menu',
        sortOrder: 3,
        visible: true,
        status: 'active',
        children: [],
        createdAt: '2026-01-05T09:07:00+08:00',
        updatedAt: '2026-06-30T10:20:00+08:00',
      },
    ],
    createdAt: '2026-01-05T09:04:00+08:00',
    updatedAt: '2026-06-30T10:20:00+08:00',
  },
  {
    id: 'm-agv-monitor',
    parentId: null,
    menuType: 'page',
    title: 'AGV 监控大屏',
    name: 'agv-monitor',
    path: '/agv/monitor',
    component: 'agv/Monitor',
    icon: null,
    sortOrder: 20,
    visible: true,
    status: 'disabled',
    children: [],
    createdAt: '2026-03-18T14:10:00+08:00',
    updatedAt: '2026-07-28T09:40:00+08:00',
  },
  {
    id: 'm-profile',
    parentId: null,
    menuType: 'page',
    title: '个人中心',
    name: 'profile',
    path: '/profile',
    component: 'profile/Profile',
    icon: null,
    sortOrder: 30,
    visible: false,
    status: 'active',
    children: [],
    createdAt: '2026-01-05T09:08:00+08:00',
    updatedAt: '2026-04-22T11:35:00+08:00',
  },
  {
    id: 'm-antd-docs',
    parentId: null,
    menuType: 'link',
    title: 'Ant Design 官网',
    name: null,
    path: 'https://ant.design',
    component: null,
    icon: 'local:ic-external',
    sortOrder: 40,
    visible: true,
    status: 'active',
    children: [],
    createdAt: '2026-05-09T16:25:00+08:00',
    updatedAt: '2026-05-09T16:25:00+08:00',
  },
]
