/**
 * @description 订单详情的常量
 * @date 2025-6-19
 */

// 订单详情的字段中英文对照
export const orderRefer = {
    id: "订单唯一标识",
    orderKey: "订单编号",
    orderName: "订单名称",
    orderType: "订单类型",
    priority: "优先级",
    appointVehicleKey: "指定车辆标识",
    appointVehicleName: "指定车辆名称",
    appointVehicleGroupKey: "指定车型组标识",
    appointVehicleGroupName: "指定车型组名称",
    orderMissions: "子任务",
    extendParameters: "扩展参数",
    executeVehicleKey: "执行车辆标识",
    executeVehicleName: "执行车辆名称",
    orderState: "订单状态",
    vehicleLockKey: "车辆锁定标识",
    vehicleLockStatus: "车辆锁定状态",
    startExecuteTime: "开始执行时间",
    finalTime: "结束执行时间",
    hangReason: "挂起原因",
    cancelReason: "取消原因",
    failReason: "失败原因",
    orderTaskKey: "订单标识",
    orderTaskName: "订单名称",
    agvKey: "车辆唯一标识",
    agvName: "车辆名称",
    theta: "车辆的旋转弧度",
    width: "宽度（m）",
    length: "长度（m）",
    centerOffset: "偏移距离（m）",
    type: "类型",
    batteryCharge: "电量（%）",
    charging: "充电中",
    connectionState: "连接状态",
    vehicleProcStatus: "车辆执行状态",
    loaded: "载货",
    dispatchState: "调度状态",
    executeTime: "开始执行时间",
    processKey: "工艺流程唯一标识",
    taskId: "外部接口唯一标识",
    loadLength: "载货长度（m）",
    loadWidth: "载货宽度（m）",
    paused: "暂停状态",
    mapId: "地图唯一标识",
    mapDescription: "地图名称",
    positionInitialized: "是否开启了定位",
    localizationScore: "定位置信度",
    normal: "agv坐标是否正常",
    fieldViolation: "安全域状态",
    batteryVoltage: "电池电压（v）",
    batteryHealth: "电池健康状态",
    reach: "电池电流(a)",
    deviationRange: "定位偏差范围值",
    estop: "紧急停车",
    createTime: "创建时间",
    updateTime: "更新时间",
    createUser: "创建人",
    updateUser: "更新人",
};
